#!/usr/bin/env python3
"""Scale analysis: is the feasibility condition a function of SIZE or of SHAPE?

Reads only committed evidence -- the calibration in `minimal_model.py` (fitted
to `reference_results/`) and the mission CSVs in `model/results/` -- and asks
what changes when the same device is built at CubeSat scale instead of
chipsat scale.

The result is that size cancels.  Drag charges for the ram silhouette and
any body-mounted power supply pays from the skin, and both the thrust demand
and the supply scale with area, so the closure condition depends on the SHAPE
ratio (skin / ram) and the altitude, not on how big the craft is.  The power
source is not part of the thruster; body-mounted solar cells are used below
only as a worked example of a skin-areal supply.

Run:  python model/scale_analysis.py [--out model/results]
"""
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import numpy as np

import minimal_model as M

REPO = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------- assumptions
# Stated here, not buried: these are engineering inputs, NOT measurements.
CELL_EFFICIENCY = 0.30        # triple-junction, end of life
ILLUMINATION_DUTY = 0.25      # orbit-average, body-mounted, no sun tracking
CELL_FRACTION_OF_SKIN = 1/3   # rest of the skin is bare collector + structure
SOLAR_CONSTANT = 1361.0       # W/m^2
DRIVE_V = 100.0               # V; F/P ~ 1/sqrt(V), so the frontier's low end

# The committed chipsat drag reference (orbit_sims config: cylinder r = h = 5 mm,
# axial pose, Cd 2.2).  Drag per unit ram area is spacecraft-independent, which
# is what lets the mission CSVs be rescaled to any body.
A_RAM_CHIPSAT = math.pi * 0.005**2

# name, ram silhouette [m^2], total skin [m^2], effective transverse radius [m]
BODIES = [
    ("chipsat O10x5.9mm (measured)",  A_RAM_CHIPSAT, 3.17e-4, 0.005),
    ("slender O10x30mm (measured)",   A_RAM_CHIPSAT, 11.0e-4, 0.005),
    ("1U cube, face-on",              0.01,          0.06,    0.050),
    ("3U end-on (10x10x30 cm)",       0.01,          0.14,    0.100),
    ("6U end-on (10x20x30 cm)",       0.02,          0.24,    0.120),
    ("12U end-on (20x20x30 cm)",      0.04,          0.36,    0.140),
]
ALTITUDES = (400, 500, 550, 600)


def drag_per_ram_area() -> dict[int, tuple[float, float]]:
    """(mean, max) drag force per m^2 of ram silhouette, from committed CSVs."""
    out = {}
    for alt in ALTITUDES:
        p = REPO / "model" / "results" / f"{alt}km_station_keeping_chipsat_model.csv"
        F = np.array([float(r["F_req_nN"]) for r in csv.DictReader(open(p))]) * 1e-9
        out[alt] = (F.mean() / A_RAM_CHIPSAT, F.max() / A_RAM_CHIPSAT)
    return out


def thick_sheath_phi(boost: float, r_eff: float, lamD: float, kTe_eV: float):
    """Float estimate for r >> lambda_D, where the OML exponent does NOT apply.

    A large body collects through a sheath that GROWS with phi rather than
    through an orbital-motion fan, so the enhancement is an area ratio,
    (r_sheath/r)^2, with a Child-Langmuir sheath r_s - r ~ lambda_D * (2*chi)^(3/4).

    ESTIMATE, not calibration: no committed run sits in this regime.  It is
    reported so the extrapolation direction is explicit and checkable.
    """
    if boost <= 1.0:
        return 0.0, 0.0
    x = (math.sqrt(boost) - 1.0) * r_eff / lamD
    chi = 0.5 * x ** (4.0 / 3.0)
    return chi * kTe_eV, chi


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=REPO / "model" / "results")
    args = ap.parse_args()

    cal = M.Calibration()
    n0, Te = 1.627e12, 1318.8                      # the committed plasma row
    K_B, Q_E, EPS0 = 1.380649e-23, 1.602176634e-19, 8.8541878128e-12
    kTe = K_B * Te / Q_E                                   # eV
    lamD = math.sqrt(EPS0 * kTe * Q_E / (n0 * Q_E**2))     # m
    j_the = M.j_the(n0, Te)
    KE = cal.kappa * (DRIVE_V - 3.0)               # phi is small for large skin
    harvest = SOLAR_CONSTANT * CELL_EFFICIENCY * ILLUMINATION_DUTY
    fd = drag_per_ram_area()

    L = []
    w = L.append
    w("# Scale analysis: does feasibility depend on size, or on shape?\n")
    w("Generated by `model/scale_analysis.py` from committed calibration and")
    w("mission CSVs. See `model/MODEL.md` for the laws and `paper/SCALING_LAWS.md`")
    w("§8c for the argument.\n")
    w("## The question\n")
    w("Every committed PIC run is a Ø10 mm body. The paper's mission table is a")
    w("100 g chipsat. Neither is a useful spacecraft. If the concept only works")
    w("at gram scale it is a curiosity; if the feasibility condition is")
    w("scale-free it is a propulsion option for CubeSats.\n")
    w("## Assumptions (engineering inputs, not measurements)\n")
    w("The power source is not part of the thruster. Body-mounted solar cells")
    w("appear here only as a worked example of a supply that scales with")
    w("skin area; any other skin-areal source changes the margin, not the")
    w("size-cancellation.\n")
    w(f"- solar cells {CELL_EFFICIENCY:.0%} efficient, {ILLUMINATION_DUTY:.0%} "
      f"orbit-average illumination → {harvest:.0f} W/m² of cell area")
    w(f"- cells cover {CELL_FRACTION_OF_SKIN:.0%} of skin (rest is bare collector + structure)")
    w(f"- drive {DRIVE_V:.0f} V (F/P ∝ 1/√V, so the frontier's low end)")
    w(f"- drag scales with ram silhouette at fixed C_d = 2.2\n")

    w("## Step 1: demand and supply are both areal\n")
    w("Drag charges for the ram silhouette; any body-mounted supply pays")
    w("from the skin (solar cells as the example).")
    w("Thrust demand, hence current, hence power, all scale with ram area, so")
    w("power per unit ram area is a property of altitude and drive alone:\n")
    w("| altitude | drag (mean) | P required |")
    w("|---|---|---|")
    for alt in ALTITUDES:
        I_per = (fd[alt][0] * 1e9) / (cal.cF * math.sqrt(KE))     # mA per m^2
        w(f"| {alt} km | {fd[alt][0]*1e6:.1f} µN/m² | "
          f"**{I_per*DRIVE_V*1e-3:.0f} W per m² of ram silhouette** |")
    w("\nHarvest per unit skin area is likewise size-free. Size cancels from")
    w("both sides. What survives is the shape ratio skin/ram.\n")

    w("## Step 2: closure by shape, at every size\n")
    w("Margin = example supply / demand. The point is that the ratio is")
    w("size-free; the absolute number is secondary.\n")
    w("| body | ram | skin/ram | cells | " + " | ".join(f"{a} km" for a in ALTITUDES) + " |")
    w("|---|---|---|---|" + "---|" * len(ALTITUDES))
    for nm, ar, sk, _r in BODIES:
        avail = harvest * sk * CELL_FRACTION_OF_SKIN
        cells = []
        for alt in ALTITUDES:
            I = (fd[alt][0] * ar * 1e9) / (cal.cF * math.sqrt(KE))
            P = I * DRIVE_V * 1e-3
            cells.append(f"{avail/P:.1f}×" if avail >= P else f"_{avail/P:.1f}×_")
        w(f"| {nm} | {ar*1e4:.2g} cm² | **{sk/ar:.0f}** | {avail:.2f} W | "
          + " | ".join(cells) + " |")
    w("\nThe slender chipsat and the 3U CubeSat return identical margins because")
    w("they have the same skin/ram ratio. Feasibility is a shape property.")
    w("The 400 km demand exceeds the example supply at every size. Supplying")
    w("it is a mission-design question, and it too is size-free.\n")

    w("## Step 3: what a useful spacecraft needs\n")
    w(f"At {DRIVE_V:.0f} V, KE = {KE:.0f} eV:\n")
    w("| body | altitude | thrust | current | power |")
    w("|---|---|---|---|---|")
    for nm, ar, sk, _r in BODIES[2:]:
        for alt in (500, 550, 600):
            F = fd[alt][0] * ar
            I = (F * 1e9) / (cal.cF * math.sqrt(KE))
            w(f"| {nm} | {alt} km | {F*1e6:.2f} µN | {I:.1f} mA | {I*DRIVE_V*1e-3:.2f} W |")

    w("\n## Step 4: collection gets easier with size\n")
    w(f"Bare thermal collection is `I = A_skin · j_the`, validated to ±1 % at rung")
    w(f"`collector.thermal`. At the committed plasma row j_the gives:\n")
    w("| body | skin | I_thermal | boost needed @600 km | regime r/λ_D |")
    w("|---|---|---|---|---|")
    for nm, ar, sk, r_eff in BODIES:
        Ith = sk * j_the * 1e3
        I = (fd[600][0] * ar * 1e9) / (cal.cF * math.sqrt(KE))
        w(f"| {nm} | {sk*1e4:.3g} cm² | {Ith:.3f} mA | {I/Ith:.1f}× | {r_eff/lamD:.1f} |")
    w("\nThe chipsat must run at χ ≈ 150–320, deep in the extrapolated")
    w("enhancement regime. A 3U needs only a few × over bare thermal, so its")
    w("float depends on the ±1 %-validated thermal flux plus a small correction.")
    w("Larger bodies need less extrapolation, not more.\n")

    w("## Step 5: the caveat, a different sheath regime\n")
    w(f"Every committed run is at r/λ_D ≈ {0.005/lamD:.1f}. CubeSat radii are")
    w("25–60 λ_D, where the OML exponent does not apply at all: the sheath is")
    w("thin and grows with φ, so enhancement is an area ratio rather than an")
    w("orbital-motion fan. Using that (Child-sheath) model instead gives an")
    w("estimate, not a calibration, since no run sits in this regime:\n")
    w("| body | altitude | boost | φ estimate |")
    w("|---|---|---|---|")
    for nm, ar, sk, r_eff in BODIES[2:]:
        for alt in (500, 550, 600):
            Ith = sk * j_the * 1e3
            I = (fd[alt][0] * ar * 1e9) / (cal.cF * math.sqrt(KE))
            phi, _chi = thick_sheath_phi(I / Ith, r_eff, lamD, kTe)
            flag = "" if phi <= 50 else " ⚠ past benign gate"
            w(f"| {nm} | {alt} km | {I/Ith:.1f}× | {phi:.0f} V{flag} |")
    w("\nBenign at 550–600 km, tightening at 500 km, past the benign gate for the")
    w("largest bodies at 500 km. Unmeasured, but the direction is favourable,")
    w("and a large-body PIC run is inexpensive: lower χ settles faster than")
    w("anything already run.\n")

    w("## Conclusion\n")
    w("The measured device is a Ø10 mm can, but the result is not about a")
    w("Ø10 mm can. Demand and supply are both areal, so the feasibility")
    w("condition reduces to a shape ratio and an altitude. CubeSat-class craft")
    w("in their natural end-on configurations sit at more favourable shape")
    w("ratios and less extrapolated collection physics than the chipsat that")
    w("was measured. The 400 km demand is scale-free too: it exceeds the")
    w("example body-mounted supply at every size.")

    out = args.out / "SCALE_ANALYSIS.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
